# Generated by Django 5.2.8 on 2025-12-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('resolu', 'Résolu'), ('en_attente', 'En attente'), ('critique', 'Critique'), ('ferme', 'Fermé'), ('non_resolu', 'Non résolu')], max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('operator_1_comment', models.TextField(blank=True, null=True)),
                ('operator_2_acknowledged', models.BooleanField(default=False)),
                ('operator_3_acknowledged', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
