# Generated by Django 5.2.8 on 2025-12-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
