# Generated by Django 5.2.7 on 2026-01-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_incident_humidity_incident_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
