# Generated by Django 5.2.7 on 2026-01-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0005_alter_incident_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
