# Generated by Django 5.2.7 on 2026-01-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0006_incident_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Incident créé'), ('counter_increment', 'Compteur incrémenté'), ('resolved', 'Incident résolu'), ('comment_added', 'Commentaire ajouté'), ('comment_updated', 'Commentaire modifié')], max_length=50)),
                ('description', models.TextField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('counter_value', models.IntegerField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='DHT.incident')),
            ],
            options={
                'verbose_name': "Historique d'incident",
                'verbose_name_plural': "Historiques d'incidents",
                'ordering': ['-timestamp'],
            },
        ),
    ]
